// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/blog/[...slug].tsx";
import * as $1 from "./routes/blog/index.tsx";
import * as $2 from "./routes/docs/[...slug].tsx";
import * as $3 from "./routes/gfm.css.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/blog/[...slug].tsx": $0,
    "./routes/blog/index.tsx": $1,
    "./routes/docs/[...slug].tsx": $2,
    "./routes/gfm.css.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
